// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9bAaWtOqN_22KjfOrDhUX10Gt-0RzXGs',
    appId: '1:678464137552:web:5e14699ea7093ff069e455',
    messagingSenderId: '678464137552',
    projectId: 'tgamobapp-f654a',
    authDomain: 'tgamobapp-f654a.firebaseapp.com',
    databaseURL: 'https://tgamobapp-f654a-default-rtdb.firebaseio.com',
    storageBucket: 'tgamobapp-f654a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU5a77UH5qkj0IDqtBRZ9H2WbxCdHoz2Y',
    appId: '1:678464137552:android:09fa3cc50738f2e369e455',
    messagingSenderId: '678464137552',
    projectId: 'tgamobapp-f654a',
    databaseURL: 'https://tgamobapp-f654a-default-rtdb.firebaseio.com',
    storageBucket: 'tgamobapp-f654a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbKRn7nZ6nf17T0ThuDXhBAg4R6GYSQU',
    appId: '1:678464137552:ios:5b22e5a8bdd0e05669e455',
    messagingSenderId: '678464137552',
    projectId: 'tgamobapp-f654a',
    databaseURL: 'https://tgamobapp-f654a-default-rtdb.firebaseio.com',
    storageBucket: 'tgamobapp-f654a.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );
}
